### ISSUE TITLE
Compression not enabled

### ISSUE THREAD

**Issue by PaintNinja** [MinecraftForge/Web#11]
While testing GZip support for https://github.com/MinecraftForge/MinecraftForge/pull/8148 , I noticed that it is not enabled server-side for https://files.minecraftforge.net .

I've estimated significant bandwidth savings with [this tool](https://tools.paulcalvano.com/compression.php) and manually checked what it would be myself to make sure it's roughly correct.

| File | Uncompressed size | Gzip | Brotli |
| ---- | --------------------- | ----- | ------ |
| Downloads homepage html | 492083 bytes | 25894 (-94.7%) | 20640 (-95.8%) |
| 1.15.2 downloads html | 735929 bytes | 36984 (-95%) | 29927 (-96%) |
| promotions_slim.json | 2500 bytes | 635 (-74.6%)  | 513 (-79.5%) |

Note that the download pages also serve up other currently-uncompressed content such as CSS, SVG and JS files which would also benefit from compression. These are not factored in here for simplicity's sake.

I assume that it was disabled to avoid compressing already-compressed jar files but with some changes to the configuration it can be set to only compress `json`, `html`, `css`, `svg`, `js`, `jsm`, `txt`, `pom`, `xml`, etc... It is also possible to set the server to compress static files once and serve them multiple times to avoid the CPU load of compressing on each request.

**Comment by LexManos** [comment]
Finally got time to figure out how to do this.
Enabled gzip compression.

Here are some numbers:
```
index_1.18.2.html
200821 13283
index_1.15.2.html
747067 40951
promotions_slim.json
2667 646
```

Enabled it for these types:
```   
        application/atom+xml
        application/geo+json
        application/javascript
        application/x-javascript
        application/json
        application/ld+json
        application/manifest+json
        application/rdf+xml
        application/rss+xml
        application/xhtml+xml
        application/xml
        font/eot
        font/otf
        font/ttf
        image/svg+xml
        text/css
        text/javascript
        text/plain
        text/xml;
```

The only concern is that this does take runtime CPU to compress the files. I did however turn on gzip_static as well, as if we make pagegen smart enough to create gziped files as well. We'll be golden.

**Comment by PaintNinja** [comment]
Hmm, looks like Nginx's default gzip compression level is around 6, while I did my testing at level 8, that probably explains the difference in estimates vs actual. Should be fixed once pagegen creates gzipped stuff for us.
