### ISSUE TITLE
HTTPS downloads

### ISSUE THREAD

**Issue by lol768** [MinecraftForge/Web#3]
Steps to reproduce:

1. Visit https://files.minecraftforge.net/ - this is loaded over TLS
1. Pick a link
1. Users are forced onto HTTP ad-laden interstitial page: `http://adfoc.us/serve/sitelinks/?id=271228&url=http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.2.2653/forge-1.12.2-14.23.2.2653-installer.jar`
1. Users are redirected back to the **plaintext** URL for the requested file - e.g. `http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.2.2653/forge-1.12.2-14.23.2.2653-installer.jar`

Ergo, download can be MitM'd.

**Comment by lol768** [comment]
Has this one been deployed @PaleoCrafter?

**Comment by marvin-roesch** [comment]
Not yet @lol768, as we're currently implementing some other changes as well and will deploy them all in one go.
